### ISSUE TITLE
log<n> crashes with negative values

### ISSUE THREAD

**Issue by crcx** [crcx/parable#23]
Test case:

    -1 log

Proposed fix:

* check for negative values and **abort** with error if they occur

**Comment by kiy** [comment]
> On 16-04-13, at 22:59 , Charles Childers <notifications@github.com> wrote:
> 
> Test case:
> 
> -1 log
> 
> Proposed fix:
> 
> 	• check for negative values and abort with error if they occur

0 or negative values

**Comment by crcx** [comment]
Thanks, I'll have this fixed tonight,
