### ISSUE TITLE
RFC: Associative Arrays

### ISSUE THREAD

**Issue by crcx** [crcx/parable#3]
Associative arrays would be useful to have in Parable. What functionality is needed, and how should they look from a syntax perspective?

Roughly something like this?

    new-assoc-array
    "- pointer"

    assoc-value-for-key
    "value string:key pointer -"

    assoc-set-value-for-key
    "string:key pointer - value"

    assoc-delete-key
    "string:key - bool"

What other functionality is needed? What iterative tools would be required? How should they be structured in memory?

**Comment by kiy** [comment]
i intend to use arrays mostly as vectors.
so it would be convenient if array elements were accessible by both numbers and keywords.
for instance,  if

[ #10 #20 #30 ] array-from-quote 'a' define

then

&a #1 array-fetch

pushes #10 on the stack.

further, if

[ 'a0'  'a1 'a2' ] array-from-quote 'an' defined

then

&a &an 'a1' array-fetch-by-name

pushes #20 on the stack.

**Comment by kiy** [comment]
so i need conversion between number and name index types. if you permit multiple names, 

[ 'a1' 'a2' 'a1' ] array-from-quote  'a1' where-first

would return  #1 .

**Comment by crcx** [comment]
Thanks; this will help me get started on this!

**Comment by crcx** [comment]
Take a look at https://gist.github.com/crcx/3bfffc3f3b3c1a448a38 and see if this works for you.

**Comment by kiy** [comment]
> On 15-04-21, at 07:41 , Charles Childers <notifications@github.com> wrote:
> 
> Take a look at https://gist.github.com/crcx/3bfffc3f3b3c1a448a38 and see if this works for you.
> 
> —
> Reply to this email directly or view it on GitHub.

now that arrays are quotes with no data type information, i prefer to treat everything as a quote. for instance, both a program and a variable would be a named quote. to define a variable i'd go, for instance,

    'ppp' 'p' define
    [ #123 'kw' &p $C ] 'x' define

now

    &x [ #0 #2 ] fetch 

gets the quote 

    [ #123 &p ] 

on the stack. or to use indexes,

    [ '0nbr' '1str' '2ptr' '3chr' ] 'index' variable!
    &x &index [ '0nbr' '2ptr' ] where fetch

in which the portion

    &index [ '0nbr' '2ptr' ] where

gives

    [ #0 #2 ]

.

to assign values,

    'qqq' 'q' define
    [ #456 &q ] &x [ '0nbr' '2ptr' ] where store

.

in the case of arrays without information on data types, 

    [ #0 '0th' #11 '1st' ] array-from-quote 'y' define
    &y [ NUMBER STRING ] quote-from-array 

would restore 

    [ #0 '0th' #11 '1st' ] 


k

**Comment by kiy** [comment]
> On 15-04-21, at 15:42 , im4u@me.com wrote:
> 
>    [ #0 '0th' #11 '1st' ] array-from-quote 'y' define
>    &y [ NUMBER STRING ] quote-from-array 
> 
> would restore 
> 
>    [ #0 '0th' #11 '1st' ] 

the data type information [ NUMBER STRING ] is applied circularly since
it is shorter than y
