### ISSUE TITLE
Bug With Slice Length

### ISSUE THREAD

**Issue by crcx** [crcx/parable#5]
After some input from Kiyoshi Yoneda, I have identified a bug in the slice length reporting of Parable.

Under normal circumstances, the get-slice-length returns the last offset in a slice. (So the actual length, minus 1, since we are using zero-based indexes). (I will clarify this in the documentation for future releases)

A case in point is an easy definition: *define*. This consists of two cells: BC_DEFINE and BC_FLOW_RETURN. And it's reported to have a length of 1.

E.g.,

    &define get-slice-length
    "returns 1"

Strings are the same:

    'hello' get-slice-length
    "returns 5"

But arrays are (oddly) reported differently. Consider:

    [ #1 #2 #3 ] array-from-quote 't' define
    &t get-slice-length
    "returns 3"

This is clearly a mistake, but I have not yet identified why this is happening, and so no fix is ready. I will be reviewing the code in detail soon, and will have a fix in place as soon as possible. Please be aware that a fix should not require a new Apologue build; I expect to be able to fix it and update the backend to incorporate it transparently.

**Comment by crcx** [comment]
So looking through the code a bit, I've noticed that the arrays have a dummy cell at the end. 

*array-push* pushes a value to the end of the array, then increases its size by 1; making things ready for the next push.

*array-pop* reduces the size by 1, then returns the last stored value

So anything other than a completely empty array has a dummy value at the end. I'm now forced to consider: do I completely rewrite the array code (again), or just document this and move on?

**Comment by kiy** [comment]
> On 15-06-02, at 11:16 , Charles Childers <notifications@github.com> wrote:
> 
> So looking through the code a bit, I've noticed that the arrays have a dummy cell at the end.
> 
> array-push pushes a value to the end of the array, then increases its size by 1; making things ready for the next push.
> 
> array-pop reduces the size by 1, then returns the last stored value
> 
> So anything other than a completely empty array has a dummy value at the end. I'm now forced to consider: do I completely rewrite the array code (again), or just document this and move on?
> 
> —
> Reply to this email directly or view it on GitHub.
 
could array management be surrogated if parable were implemented in a lisp or a scheme variant?
many lisps such as racket come with arrays.
perhaps garbage collection could also be surrogated.

**Comment by kiy** [comment]
> On 15-06-02, at 07:25 , Charles Childers <notifications@github.com> wrote:

> Under normal circumstances, the get-slice-length returns the last offset in a slice. (So the actual length, minus 1, since we are using zero-based indexes). (I will clarify this in the documentation for future releases)

i'm not sure if get-slice-length should return the last offset or the actual length.
to me the size of the set {0, ..., n} is not n but n + 1.

**Comment by crcx** [comment]
In the latest commit (https://github.com/crcx/parable/commit/c23848a2fc6c0083f92d72feb74ab90ab9bc49eb)  I have partially addressed this.

I have renamed:

**get-slice-length** to **get-last-index**
**set-slice-length** to **set-last-index**
**slice-length** to **slice-last-index**

And added:

**get-slice-length**
**slice-length**

The **-index** functions will return the last addressable index in a slice. The **-length** functions will now return the actual number of items in a slice.

So:

    'hello'

Has a length of 5, and a last index of 4.

----

This issue isn't over yet. Arrays are still functioning, but still have the wrong reported lengths. I'm continuing my investigations, but at this point am seriously considering rewriting the code again.

**Comment by crcx** [comment]
> could array management be surrogated if parable were implemented in a lisp or a scheme variant?
> many lisps such as racket come with arrays.
> perhaps garbage collection could also be surrogated.

I see a couple of issues with this:

* I'm not very experienced with Lisp / Scheme. (I've dabbled enough to be able to follow along with some code, with the docs handy, and to implement Ngaro [Retro's VM] in Common Lisp, but I'm far from comfortable with using it)
* Lisp's arrays wouldn't help unless Parable exposed them as the base slice construct
* Using the host garbage collection would fall into the above I think. It'd also likely be difficult to keep things tracked reliably. The current garbage collector doesn't seem to be a problem, though it is extremely conservative in nature.

**Comment by kiy** [comment]
i see.
thank you for the reply.

**Comment by crcx** [comment]
So the dummy cell is caused by the structure of arrays.

**array-push** will append a dummy cell after appending the value to increase the length of the slice so the next push doesn't overwrite the actual last value. **array-pop** discards the dummy cell. I'll need to consider how to deal with this, since strings are no longer zero terminated, treating them as arrays may be more problematic (as there's no dummy cell).
